#tasks.yaml
research_business_task:
  description: >
    Analyze the content of the provided URLs to identify potential leads.
    For each URL, extract information about companies that could benefit from services related to: {user_keywords}.
    Prioritize companies that explicitly mention a need for these services or have related activities within the content of these URLs.
    Gather the following information for each company found in the URLs:
      - Company Name
      - Website (valid URL, if found within the analyzed content or linked from it)
      - Brief Description (based on the URL content)
      - Contact Information (email, social media links, if found within the URL content or linked from it)
    URLs to analyze: {company_urls} # Input URLs

  expected_output: >
    A list of dictionaries, where each dictionary contains validated and enriched data
    for a single company identified within the provided URLs, including its name, contact information,
    brief description, and website (if found). Indicate if the information was extracted from the given URL or linked from it.
  agent: business_researcher

create_sales_email_task:
  description: >
    Create a highly personalized sales email for the target company.
    Connect the company's specific needs and challenges (from the research)
    with the user's skills and services. Use a professional but friendly tone.
    Keep the email concise (no more than 200 words). Include a clear call
    to action (CTA), proposing a specific topic for a meeting. The output should be plain text.
  expected_output: >
    A plain text sales email, ready to be sent, including a subject line and body.
  agent: sales_copywriter
  context: [research_business_task]

create_report_task:
  description: >
    Consolidate the companies information, email content, and user profile data.
    Validate the data using Pydantic models. Create a final report containing all
    gathered and validated information.
  expected_output: >
    A final report in markdown containing for each companie his 'status' (success or validation_error), 'data' (if successful),
    'errors' (if validation fails), and 'timestamp'. The 'data' field should contain 'company_info',
    'email_content', and 'user_info' all formated as a markdown report.
  agent: reporting_analyst
  context: [create_sales_email_task,research_business_task]
  output_file: "output/report.md"