research_business_task:
  description: >
    Conduct detailed research on companies in {province}, Argentina, within the {industry} sector.
    Identify companies that could benefit from services related to: {user_keywords}.
    Prioritize companies that explicitly mention a need for these services or have related activities.
    If a company name is provided ({company_name}), focus specifically on that company.
    Gather the following information:
      - Company Name
      - Website (valid URL)
      - Brief Description
      - Contact Information (email, social media links)
  expected_output: >
    A list of dictionaries, where each dictionary contains validated and enriched data
    for a single company, including contact information.
  agent: business_researcher
  
create_sales_email_task:
  description: >
    Create a highly personalized sales email for the target company.
    Connect the company's specific needs and challenges (from the research)
    with the user's skills and services. Use a professional but friendly tone.
    Keep the email concise (no more than 200 words). Include a clear call
    to action (CTA), proposing a specific topic for a meeting. The output should be plain text.
  expected_output: >
    A plain text sales email, ready to be sent, including a subject line and body.
  agent: sales_copywriter
  context: [research_business_task]  # AQUI: email_task depende de research_business_task

create_report_task:
  description: >
    Consolidate the company information, email content, and user profile data.
    Validate the data using Pydantic models. Save the validated company data
    (lead) to the Supabase database. Create a final report containing all
    gathered and validated information.
  expected_output: >
    A dictionary containing 'status' (success or validation_error), 'data' (if successful),
    'errors' (if validation fails), and 'timestamp'. The 'data' field should contain 'company_info',
    'email_content', and 'user_info'.
  agent: reporting_analyst
  context: [create_sales_email_task]  # AQUI: report_task depende de create_sales_email_task
  output_file: "output/report.md"